### ISSUE TITLE
Verification Issue

### ISSUE THREAD

**Issue by adwilliamson** [Appgutta/AGCalendar#10]
Hi,
I have been using your module without any issues for the past 6 months. A couple of days ago, one of my apps that is still in development started coming up with a "Verification Issue- Unlicensed modules(s) detected".... I have tracked it down to this module (I am only using 1 other). I have tried re-installing the module, creating a new project and still the error persists.

Any ideas?

thanks.

**Comment by ChrisRM** [comment]
Can you please verify that this is fixed by creating a new project and including the module ? The problem happened when I uploaded the module to the marketplace. I removed it from there now, so it should be good to go again. Sorry for the inconvenience.

**Comment by ChrisRM** [comment]
Should work for your current project aswell by the way. No need to create a new project.

**Comment by adwilliamson** [comment]
Hi Chris,
Appreciate your quick reply. Still having issues. Have tried creating a new project and importing a newly downloaded version of the module. If could easily be something I am doing wrong, but I completely deleted the module and started again. Any other ideas?

thanks.

**Comment by ChrisRM** [comment]
Theres nothing wrong with your project, its the module. I've learned that when uploading the module to the Appcelerator Marketplace, the module wont run unless you download it from Marketplace. I have deleted the module from marketplace, so its a matter of time before it starts working again, I think. If it dont, I'll contact Appcelerator and ask them to remove it from their cache.

**Comment by adwilliamson** [comment]
Hi Chris,
Any news? Pretty keen to get an app submitted this week with the calendar in it, but still getting these issues. Is it possible to generate a new guid? Would that fix it?

thanks.

**Comment by adwilliamson** [comment]
found this if it helps...
http://developer.appcelerator.com/blog/2011/09/module-verification.html
